services:
#    greeter.example:
#        class: GreeterBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]


    greeter.scenario.flow:
        class: GreeterBundle\Scenario\GreeterScenario
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: sylius.process.scenario, alias: greeter }